# Generated by Django 2.2.3 on 2019-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadTimestamp', models.DateTimeField()),
                ('loadType', models.CharField(max_length=3)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
