# Generated by Django 2.2.3 on 2019-07-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tph',
            name='humidity',
            field=models.DecimalField(db_column='humidity', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tph',
            name='loadTimestamp',
            field=models.DateTimeField(db_column='ts'),
        ),
        migrations.AlterField(
            model_name='tph',
            name='loadType',
            field=models.CharField(db_column='type', max_length=3),
        ),
        migrations.AlterField(
            model_name='tph',
            name='pressure',
            field=models.DecimalField(db_column='pressure', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tph',
            name='temperature',
            field=models.DecimalField(db_column='temperature', decimal_places=2, max_digits=8),
        ),
        migrations.AlterModelTable(
            name='tph',
            table='tph',
        ),
    ]
