#ifndef _INCL_RXTXMSGDEF
#define _INCL_RXTXMSGDEF

#define COMMAND_PING				0x02
#define COMMAND_WEATHER				0x03
#define COMMAND_LEDON				0x31		// '1'
#define COMMAND_LEDOFF				0x30		// '0'
#define COMMAND_ADC					0x04
#define COMMAND_AVG_WIND_SPEED		0x05
#define COMMAND_MAX_WIND_SPEED		0x06
#define COMMAND_AVG_RAINFALL		0x07
#define COMMAND_MAX_RAINFALL		0x08

#endif
